CREATE DATABASE IF NOT EXISTS wordpress;
CREATE USERs 'MYSQL_USER'@'%' IDENTIFIED BY 'MYSQL_PASSWORD';
GRANT ALL PRIVILEGES ON wordpress.* TO 'MYSQL_USER'@'%' WITH GRANT OPTION;
ALTER USER 'root'@'localhost' IDENTIFIED BY 'MYSQL_ROOT_PASSWORD';
FLUSH PRIVILEGES;